name: "Extract and Package PyPI Requirements"
description: "Extract PyPI requirements from a pixi.lock file, install them, and zip the site-packages."

inputs:
  lock_file_path:
    description: "Path to the pixi.lock file"
    required: false
    default: "pixi.lock"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"

    - name: Install pixi-requirements CLI
      shell: bash
      run: |
        pip install git+https://github.com/cfobel/pixi-site-packages.git@v0.1.1

    - name: Create site-packages directory
      shell: bash
      run: mkdir -p site-packages

    - name: Install packages into target directory
      shell: bash
      run: |
        for r in $(pixi-requirements "${{ inputs.lock_file_path }}" --platform linux-64); do
          echo "Installing $r..."
          pip install --upgrade --no-deps -t site-packages "$r"
        done

    - name: Create zip archive
      shell: bash
      run: |
        cd site-packages
        zip -r ../site-packages.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: site-packages
        path: site-packages.zip
