name: Build Job Reusable

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true

      - name: Install dependencies
        run: pixi install

      - name: Lint code
        run: pixi run lint

      - name: Run tests
        run: pixi run test

      - name: Build project
        run: pixi run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/*
