name: Build Workflow

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "refs/tags/**"

jobs:
  call-build-job:
    uses: cfobel/pixi-site-packages/.github/workflows/build.yml@34bdcfd351c6169390abd9098d39817521b3d369l
