name: Release Workflow

on:
  push:
    tags:
      - '**'

jobs:
  call-build-job:
    uses: cfobel/pixi-site-packages/.github/workflows/build.yml@main

  release:
    needs: call-build-job
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: dist

      - name: List Artifact Contents
        run: ls -R dist

      - name: Create GitHub Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          name: ${{ env.GITHUB_WORKFLOW }}
          files: dist/*
          gzip: false