name: Build Site Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run custom action
        uses: ./.github/actions/pixi-site-packages
        with:
          lock_file_path: "pixi.lock"
